import type {Metadata} from 'next';

export const metadata:Metadata={
  title:'Weniger Gehalt, mehr Homeoffice – lohnt sich das? 2026 | JobWert',
  description:'Vergleiche weniger Gehalt mit mehr Homeoffice, geringeren Pendelkosten und weniger Pendelzeit. Sieh Geld- und Zeiteffekt getrennt.',
  alternates:{canonical:'/weniger-gehalt-mehr-homeoffice/'},
};

export default function Page(){return <main className="landing"><div className="brand"><a href="/"><strong>Job</strong>Wert</a><small> · Bessere Entscheidungen. Mehr vom Leben.</small></div><header><h1>Weniger Gehalt, mehr Homeoffice: Kann sich das trotzdem lohnen?</h1><p>Ein niedrigeres Bruttogehalt kann durch geringere Pendelkosten und weniger gebundene Zeit teilweise ausgeglichen werden. Ob das Angebot zu dir passt, hängt deshalb nicht nur vom Gehalt ab.</p><a className="cta" href="/#rechner">Homeoffice-Angebot vergleichen</a></header><section className="details"><h2>Was bleibt finanziell wirklich übrig?</h2><p>Vergleiche das geschätzte Netto beider Jobs und berücksichtige die von dir eingetragenen Wohn-, Pendel- und sonstigen regelmäßigen Kosten. So erkennst du, wie groß der tatsächliche monatliche Unterschied beim verfügbaren Einkommen ist.</p><h2>Wie viel Zeit gewinnst du durch Homeoffice?</h2><p>Weniger Bürotage bedeuten in vielen Fällen weniger Pendelzeit. JobWert berechnet aus deinen Angaben den wöchentlichen Gesamtzeitaufwand aus Arbeit und Pendeln und zeigt zusätzlich den jährlichen Zeitunterschied.</p><h2>Wird Homeoffice automatisch in Geld umgerechnet?</h2><p>Nein. JobWert bewertet Freizeit nicht pauschal in Euro. Der finanzielle Effekt und der Zeitgewinn werden getrennt gezeigt. Dadurch kannst du selbst entscheiden, ob dir beispielsweise fünf Stunden mehr freie Zeit pro Woche einen bestimmten Gehaltsunterschied wert sind.</p><h2>Wann kann weniger Gehalt trotzdem sinnvoll sein?</h2><p>Ein Angebot kann trotz niedrigerem Brutto interessant sein, wenn deine laufenden Kosten sinken, du deutlich weniger pendelst oder deine Wochenbelastung zurückgeht. Umgekehrt sollte ein höherer Homeoffice-Anteil nicht automatisch als Vorteil gelten, wenn dein verfügbares Einkommen dadurch stark fällt.</p><h2>Typische Fragen</h2><h3>Reduziert JobWert meine Pendelkosten automatisch bei mehr Homeoffice?</h3><p>Nein. Die monatlichen Pendelkosten trägst du selbst ein. So bleibt der Vergleich transparent und berücksichtigt deine tatsächliche Situation.</p><h3>Kann ich Homeoffice und Arbeitszeit gleichzeitig vergleichen?</h3><p>Ja. Beide Jobs können unterschiedliche Wochenarbeitszeiten, Arbeitstage, Homeoffice-Tage und Pendelzeiten haben.</p><h3>Was, wenn das neue Angebot mehr Homeoffice, aber auch längere Arbeitszeiten hat?</h3><p>Genau dafür werden Zeit und Geld separat dargestellt. Der Rechner zeigt dir, ob die geringere Pendelzeit durch längere Arbeitszeit wieder aufgezehrt wird.</p><p><a href="/homeoffice-vs-buero-rechner/">Homeoffice und Büro direkt vergleichen</a> · <a href="/pendelkosten-jobwechsel/">Pendelkosten beim Jobwechsel prüfen</a> · <a href="/jobwechsel-rechner/">Gesamten Jobwechsel berechnen</a></p></section><footer><span>© 2026 JobWert</span><a href="/datenschutz">Datenschutz</a><a href="/impressum">Impressum</a></footer></main>}
