import type {Metadata} from 'next';

export const metadata:Metadata={
  title:'Methodik 2026 – So rechnet JobWert | JobWert',
  description:'So schätzt JobWert Netto, Wohnkosten, Lebenshaltung, Pendelkosten, Pendelzeit, Break-even und Zielgehalt für einen schnellen Jobvergleich.',
  alternates:{canonical:'/methodik/'},
};

export default function Page(){return <main className="landing"><div className="brand"><a href="/"><strong>Job</strong>Wert</a></div><h1>So rechnet JobWert</h1><p>JobWert ist ein Entscheidungsrechner für Jobwechsel und Jobangebote. Der Schnellvergleich soll mit wenigen Angaben eine belastbare Orientierung geben. Fehlende Werte werden deshalb bewusst geschätzt und sichtbar als Schätzung gekennzeichnet. Du kannst diese Werte im Ergebnis unter „Details anpassen“ durch deine echten Zahlen ersetzen.</p><a className="cta" href="/#rechner">Zum Jobvergleich</a><section className="details">
<h2>Lohnsteuer 2026</h2><p>Für die Schätzung von Lohnsteuer und Solidaritätszuschlag verwendet JobWert eine Implementierung des Programmablaufplans des Bundesministeriums der Finanzen für 2026. Der BMF-Programmablaufplan beschreibt die maschinelle Berechnung der vom Arbeitslohn einzubehaltenden Lohnsteuer, des Solidaritätszuschlags und der Bemessungsgrundlage für die Kirchenlohnsteuer.</p><p><a href="https://www.bundesfinanzministerium.de/Content/DE/Downloads/Steuern/Steuerarten/Lohnsteuer/Programmablaufplan/2025-11-12-PAP-2026.html" rel="external">Quelle: Bundesministerium der Finanzen – Programmablaufpläne 2026</a></p>
<h2>Sozialabgaben</h2><p>Die Sozialversicherungsbeiträge werden als Näherungsmodell für einen regulär gesetzlich versicherten Arbeitnehmer außerhalb Sachsens berechnet. Der Schnellvergleich startet mit neutralen Standardannahmen. Persönliche Details wie Kinder, Kirchensteuer und der KV-Zusatzbeitrag können anschließend angepasst werden.</p><p><a href="https://www.bmas.de/DE/Service/Gesetze-und-Gesetzesvorhaben/sozialversicherungs-rechengroessenverordnung-2026.html" rel="external">Quelle: Bundesministerium für Arbeit und Soziales – Rechengrößen 2026</a></p>
<h2>Wohnkosten: Stadtmodell statt Scheingenauigkeit</h2><p>Im Schnellvergleich fragt JobWert nicht nach einer zukünftigen Miete, die viele Nutzer noch gar nicht kennen. Stattdessen wird aus Wohnort und Wohnsituation eine grobe warme Monatsmiete abgeleitet. Das Modell arbeitet mit typischen Wohnflächen für Alleinlebende, Paare und Familien sowie relativen Kostenfaktoren für größere deutsche Arbeitsmärkte. Für nicht hinterlegte Orte wird ein Deutschland-Basiswert verwendet und die Unsicherheit bewusst vergrößert.</p><p>Die Wohnkostenschätzung ist ausdrücklich kein Mietspiegel, keine Angebotsmiete und keine Aussage darüber, welche konkrete Wohnung du bekommen wirst. Bei einem Umzug dient sie nur dazu, den möglichen Kostensprung zwischen zwei Orten sichtbar zu machen. Offizielle Mietspiegel zeigen zudem in der Regel ortsübliche Vergleichsmieten für bestehende Mietverhältnisse und sind daher nicht automatisch mit einer zukünftigen Neuvermietung gleichzusetzen.</p>
<h2>Lebenshaltungskosten ohne Miete</h2><p>Zusätzlich zur Miete verwendet JobWert einen vorsichtigen Haushalts-Grundwert für regelmäßige Lebenshaltungskosten ohne Miete. Die Wohnsituation bestimmt den Ausgangswert; ein kleiner Stadtfaktor berücksichtigt, dass Alltagskosten regional unterschiedlich sein können. Dieser Bestandteil hat bewusst eine geringere regionale Spreizung als die Miete.</p>
<h2>Pendelkosten und Pendelzeit</h2><p>Für Wege innerhalb einer Stadt verwendet der Schnellvergleich typische Zeit- und Kostenannahmen je Verkehrsmittel und Bürotagen. Wenn du nicht umziehst und JobWert beide Städte kennt, wird für einen neuen Arbeitsort zusätzlich eine grobe Luftlinienentfernung mit Wegfaktor verwendet. Auto wird mit einem pauschalen Kilometerkostensatz modelliert; für ÖPNV/Bahn wird eine Orientierungsschätzung verwendet. Fahrrad und Fußweg werden mit sehr niedrigen direkten Kosten angesetzt.</p><p>Das ersetzt keine Routen- oder Fahrplanauskunft. Baustellen, Parkkosten, Deutschlandticket, ICE-Sparpreise, BahnCard, Firmenwagen, Jobticket und individuelle Fahrzeugkosten können das reale Ergebnis deutlich verändern. Deshalb lassen sich Kosten und Fahrzeit im Ergebnis überschreiben.</p>
<h2>Warum JobWert eine Spanne zeigt</h2><p>Eine einzelne Zahl würde bei geschätzter Miete und Pendelkosten eine Genauigkeit vortäuschen, die es nicht gibt. JobWert berechnet deshalb im Schnellvergleich eine vorsichtige Ergebnis-Spanne. Liegt selbst die untere Grenze klar im Plus, lautet das Fazit „lohnt sich voraussichtlich“. Liegt selbst die obere Grenze im Minus, lautet das Fazit „lohnt sich voraussichtlich nicht“. Schneidet die Spanne den Break-even, wird das Ergebnis als zu knapp für eine klare Aussage markiert.</p>
<h2>Verfügbares Einkommen, Break-even und Mindestgehalt</h2><p>Für den Vergleich werden vom geschätzten monatlichen Netto Wohnkosten, Pendelkosten und weitere modellierte Lebenshaltungskosten abgezogen. Das Break-even-Gehalt ist das Bruttojahresgehalt, bei dem das neue Angebot ungefähr dasselbe verfügbare Einkommen wie die aktuelle Situation liefert. Im Schnellvergleich zeigt JobWert zusätzlich ein Mindestgehalt für einen kleinen echten Vorteil von rund 100 € mehr verfügbarem Einkommen pro Monat.</p>
<h2>Arbeits- und Pendelzeit</h2><p>Die Pendelzeit wird aus einfacher Fahrzeit und Bürotagen abgeleitet. Im Schnellvergleich wird zunächst mit 40 Wochenstunden und fünf Arbeitstagen gerechnet. Unter „Details anpassen“ kannst du die Wochenarbeitszeit ändern. Geld und Zeit werden nicht künstlich zu einem einzigen Euro-Wert verschmolzen; JobWert zeigt beide Auswirkungen getrennt und ergänzt einen effektiven Stundenwert als zusätzliche Orientierung.</p>
<h2>Warum das Netto nur eine Schätzung ist</h2><p>Eine reale Lohnabrechnung kann von weiteren persönlichen Merkmalen abhängen. JobWert bildet nicht jede steuerliche oder sozialversicherungsrechtliche Konstellation ab. Insbesondere ist die einfache Kinderangabe kein Kinderfreibetragsfaktor; sie wird im Modell für die Pflegeversicherung verwendet.</p>
<h2>Datenschutz im Rechner</h2><p>Die eigentlichen Vergleichsdaten werden im Browser verarbeitet. Für das Teilen eines Vergleichs können Werte in die URL geschrieben werden. Teile einen solchen Link daher nur, wenn die enthaltenen Angaben weitergegeben werden dürfen.</p>
<h2>Weiterführende Rechner</h2><p><a href="/jobwechsel-rechner">Jobwechsel Rechner</a> · <a href="/jobangebote-vergleichen">Jobangebote vergleichen</a> · <a href="/gehaltserhoehung-rechner">Gehaltserhöhung Rechner</a> · <a href="/gehaltsverhandlung">Gehaltsverhandlung vorbereiten</a></p></section><footer><span>© 2026 JobWert</span><a href="/">Rechner</a><a href="/datenschutz">Datenschutz</a><a href="/impressum">Impressum</a></footer></main>}
